services:
  postgres:
    image: postgres:16-alpine
    env_file:
      ./configs/dev.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USERNAME} -d $${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: ${ENV}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
      DB_DRIVER: ${DB_DRIVER}
      DB_SOURCE: "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      ./configs/dev.env

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data: